export const actionType={
    USER_LOGIN:"USER_LOGIN",
    USER_LOGOUT:"USER_LOGOUT",
    GET_DATA_REQUEST:"GET_DATA_REQUEST",
    GET_DATA_SUCCESS:"GET_DATA_SUCCESS",
    GET_DATA_FAILURE:"GET_DATA_FAILURE"
}